### ISSUE TITLE
Add an ability to round to custom number of decimal points

### ISSUE THREAD

**Issue by mickeyvip** [EvanHahn/HumanizeDuration.js#73]
Hi and thank you!

I think it would be a great addition to have be able to round to a specific number of decimal places:

now:

``` javascript
var smallDuration = 499;
var viewValue = humanizeDuration(smallDuration); // -> "0.499 seconds"
var viewValueRounded = humanizeDuration(smallDuration, {round: true}); // -> "0 seconds"
```

would be nice:

``` javascript
var smallDuration = 499;
var viewValueRounded = humanizeDuration(smallDuration, {round: 1}); // -> "0.5 seconds"
```

**Comment by EvanHahn** [comment]
Could this just proxy to `toFixed`?

```js
(0.499).toFixed(1)  // => "0.5"
(0.499).toFixed(2)  // => "0.50"
(0.499).toFixed(3)  // => "0.499"
```

**Comment by mickeyvip** [comment]
If I proxy it to `.toFixed()` I would lose the time units.

**Comment by EvanHahn** [comment]
If you'd like to submit a PR, feel free!

**Comment by marcj** [comment]
That would be awesome :)

**Comment by topr** [comment]
Perhaps `round` param could take a function instead of boolean value. This would be far more flexible as I need for example to cut off seconds, not to round them.

**Comment by EvanHahn** [comment]
@topr Agreed. One thing that makes this tricky is how rounding affects other numbers. For example, what happens if you do something like this?

```js
humanizeDuration(123456, {
  round: function () {
    return 0
  }
})
```

**Comment by topr** [comment]
Would it be an issue? Not sure but I guess result should then be the same
as if 0 would be passed in instead of 123456, shouldn't it?

I don't think the lib should care or prevent such a misuse. If someone
passes a custom impl then it's his responsibility to make it right.

I was mostly thinking about use cases like `humanizeDuration(123456, {
round: Math.floor })`

On 2 Feb 2017 22:58, "Evan Hahn" <notifications@github.com> wrote:

@topr <https://github.com/topr> Agreed. One thing that makes this tricky is
how rounding affects other numbers. For example, what happens if you do
something like this?

humanizeDuration(123456, {
  round: function () {
    return 0
  }
})

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/EvanHahn/HumanizeDuration.js/issues/73#issuecomment-277111919>,
or mute the thread

**Comment by EvanHahn** [comment]
What if you're trying to humanize the largest 2 units and then you choose to round down? For example, your result might start like this before you round and do your cutoff:

> 2 weeks, 6 days, 23 hours, 59 minutes

Depending on how you round, the results can be different. If you round up, you could get "3 weeks". If you round down, you should get "2 weeks, 6 days". These rounding issues can cascade, which is why it's tricky (but not impossible).

**Comment by vincentjames501** [comment]
+1. This would be nice.

**Comment by stevenvachon** [comment]
Do it.

**Comment by EvanHahn** [comment]
Lots of people seem to want this feature and things around it. I want to do it but I'm worried it gets _really_ hairy with lost of corner cases. What do people think about [my comment from February](https://github.com/EvanHahn/HumanizeDuration.js/issues/73#issuecomment-277445601)?

**Comment by stevenvachon** [comment]
```js
{
  units: ['d','m','s'],
  unitsConfig: {
    m: {
      measure: 30,  // unitMeasures
      round: value => 1
    }
  }
}
```

**Comment by EvanHahn** [comment]
This library is in maintenance mode, so I won't be adding new features, sadly. I'm going to close this issue. See #120 for more.

**Comment by stevenvachon** [comment]
Use [pretty-ms](https://npmjs.com/pretty-ms) instead.
