### ISSUE TITLE
change language globally

### ISSUE THREAD

**Issue by marqu3z** [EvanHahn/HumanizeDuration.js#99]
I find useful to have a method allowing to change the language for all the humanization.
The library allow to pass an option to set the language, but it is one shot.

```
humanizeDuration(10000, {language: "es"}) // spanish one shot
humanizeDuration(10000) // back to english as it is default global lang
```

Right now i tried a workaround for changing the language globally, but it sounds a little dirty:
```
humanizeDuration = humanizeDuration.humanizer({language: "es"})
```

It could be really helpful to have a method to change the language globally.
Like `setLanguage()`, `setPreferredLanguage()` or `setDefaultLanguage()` or whatever it could make sense!

**Comment by EvanHahn** [comment]
This is intentional.

Imagine a library called `CuantosDías.js` that tells you how many days are in a number of milliseconds. Here's how it might work:

```js
cuantosDias(86400000)      // => '1 día'
cuantosDias(86400000 * 3)  // => '3 días'
```

You could build it with a `defaultLanguage` property:

```js
var humanizeDuration = require('humanize-duration')

humanizeDuration.defaultLanguage = 'es'

// ¿cuántos días hay en `ms` milisegundos?
function cuantosDias (ms) {
  return humanizeDuration(ms, {
    units: ['d']
  })
}

module.exports = cuantosDias
```

But what happens if you change the default language somewhere?

```js
cuantosDias(86400000)      // => '1 día'

humanizeDuration.defaultLanguage = 'ko'

cuantosDias(86400000 * 3)  // => '3 일'
```

This can cause unexpected results, which is why I removed this feature.
